### ISSUE TITLE
Goomba emulator : deactivate "clean boot" screen

### ISSUE THREAD

**Issue by Wapameepto** [veikkos/omega-kernel#4]
Hi,
is it possible to deactivate the "clean Boot" screen and start instantly after selecting the game?

![IMG_1408](https://user-images.githubusercontent.com/64494076/80522206-7cc60380-898c-11ea-93da-a3b65bcbbbaf.jpg)

**Comment by veikkos** [comment]
I think it would be possible for emulated (GB, CGB etc.) games which have game menu with single "clean boot" option. Since GBA games have options to choose from that cannot be skipped.

Here is a version built from [skip-empty-menu](https://github.com/veikkos/omega-kernel/tree/skip-empty-menu) branch you can try out.

[k1.06_fw7-veikkos4-qm1.zip](https://github.com/veikkos/omega-kernel/files/4553322/k1.06_fw7-veikkos4-qm1.zip)

**Comment by Wapameepto** [comment]
Thanks. It works perfekt. One last thing. Can you please combine this version with this one https://github.com/veikkos/omega-kernel/issues/2 ?

**Comment by veikkos** [comment]
There you go.

[k1.06_fw7-veikkos4-qm2.zip](https://github.com/veikkos/omega-kernel/files/4553483/k1.06_fw7-veikkos4-qm2.zip)

**Comment by Wapameepto** [comment]
Great work. Thank you so much.

**Comment by veikkos** [comment]
I'll integrate this to actual release after I'm done with #2.

**Comment by veikkos** [comment]
Fix released in [version 5](https://github.com/veikkos/omega-kernel/releases/tag/k1.06_fw7-veikkos5). Thanks for the suggestion. Feel free to open follow-up suggestions/issues.
